### ISSUE TITLE
where is the supplementary material mentioned in paper

### ISSUE THREAD

**Issue by Shiwen615** [brandleyzhou/DIFFNet#14]
At the bottom of page 9 said "The corresponding images are shown in the supplementary material." but I can't find the supplementary material section in this paper.
is there any misunderstanding on my part?
thanks for your time

**Comment by brandleyzhou** [comment]
you can access the supplementary material via https://drive.google.com/file/d/1nqbslbsrZZCijzJcPuSZ97UgY-9pPQZj/view?usp=sharing

**Comment by Shiwen615** [comment]
Thanks for your response
