### ISSUE TITLE
Saved trained models

### ISSUE THREAD

**Issue by MohsenMoradiArt** [brandleyzhou/DIFFNet#18]
Hi, Thank you for sharing your amazing code. I run the training code and it was trained for 20 epochs but I don't know where the models are saved? also your code save each epoch results separately or only save the last epoch? and the last question, where can I change the number of epochs for training?

**Comment by brandleyzhou** [comment]
You can change training configs in options.py.(e.g. save path, training epoch.). And a model is saved per epoch.

**Comment by MohsenMoradiArt** [comment]
> You can change training configs in options.py.(e.g. save path, training epoch.). And a model is saved per epoch.

Thank you for your prompt response. However, I cannot find any single epoch saved on my pc. If I don't have a folder (by default is "mdp") and also in the "start2train.sh" file the model name is set to "mono_model", then the code is not creating a folder automatically to save the epochs?

**Comment by MohsenMoradiArt** [comment]
> You can change training configs in options.py.(e.g. save path, training epoch.). And a model is saved per epoch.

Thank you for your prompt response. However, I cannot find any single epoch saved on my pc. If I don't have a folder (by default is "mdp") and also in the "start2train.sh" file the model name is set to "mono_model", then the code is not creating a folder automatically to save the epochs?

**Comment by MohsenMoradiArt** [comment]
> 

Thank you so much, it was saving in a different drive, I found them.
