### ISSUE TITLE
Changing Input Size

### ISSUE THREAD

**Issue by ArminMasoumian** [brandleyzhou/DIFFNet#19]
Hi,
The provided code gives the results for 640x192 image size. where can I change it to the original size input (1024x320) and train with that?
Also, it seems that you add an internal feature fusion to the original HRNet, I would like to remove that and test it with the original HRNet. In the "test_hr_encoder.py" I tried to remove "mixed_features" and only return "features", but in the decoder, I get an error. Is there any way to train your model with the original HRNet?

**Comment by brandleyzhou** [comment]
Training configuration is in the options.py. If you want to know the performance of the original HRNet, you can have a look at the ablation table in our paper. for reproducing, we keep the depth decoder unchanged and replace the resnet18 depth encoder with original hrnet

**Comment by ArminMasoumian** [comment]
> Training configuration is in the options.py. If you want to know the performance of the original HRNet, you can have a look at the ablation table in our paper. for reproducing, we keep the depth decoder unchanged and replace the resnet18 depth encoder with original hrnet

Just change the default values of "Width" and "Height" on option.py?

**Comment by ArminMasoumian** [comment]
> yes

Tnx
