### ISSUE TITLE
cannot reproduced results mentioned in the paper

### ISSUE THREAD

**Issue by ArminMasoumian** [brandleyzhou/DIFFNet#20]
Hi, I trained your model with 640x192 and 1025x320 input sizes, but the results are different from what you mentioned in the paper.

Here are the results I got:

-> Computing predictions with size 640x192
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.108  &   0.792  &   4.589  &   0.186  &   0.889  &   0.963  &   0.982  \\

-> Computing predictions with size 1024x320
   abs_rel |   sq_rel |     rmse | rmse_log |       a1 |       a2 |       a3 | 
&   0.103  &   0.909  &   4.642  &   0.183  &   0.899  &   0.965  &   0.982  \\

And here are the results mentioned in the paper:

![Screenshot_1](https://user-images.githubusercontent.com/74140596/173186344-6aaeaf46-796c-47a5-bdcc-51e976ded36f.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/74140596/173186354-6116aeeb-4b80-4f4c-b3be-c2baa811ddb4.jpg)

I don't know what cause this difference, because when I used your pre-trained weights for evaluation, I got the same results as yours. do you have any idea why? maybe the code has slightly changed? or a different version of the torch can cause this?

**Comment by brandleyzhou** [comment]
the torch version is a factor.I use 1.1.0 for these experiments. And another point is the batch size, I set 16 for 640x192 and 8 for 1024x320 on single rtx6000 GPU

**Comment by Junyu-Z** [comment]
> the torch version is a factor.I use 1.1.0 for these experiments. And another point is the batch size, I set 16 for 640x192 and 8 for 1024x320 on single rtx6000 GPU

Hi author, I got worse results on a V100 GPU with torch 1.1.0 and I guess the version of other packages can also influence the results. So can you share the conda environment '*.yaml' file with us?

**Comment by brandleyzhou** [comment]
> 

what numbers you've got? I have V100 and I will train a model on that to see what gonna happen

**Comment by brandleyzhou** [comment]
> > the torch version is a factor.I use 1.1.0 for these experiments. And another point is the batch size, I set 16 for 640x192 and 8 for 1024x320 on single rtx6000 GPU
> 
> Hi author, I got worse results on a V100 GPU with torch 1.1.0 and I guess the version of other packages can also influence the results. So can you share the conda environment '*.yaml' file with us?

what numbers you've got? I have V100 and I will train a model on that to see what gonna happen

**Comment by Junyu-Z** [comment]
> > > the torch version is a factor.I use 1.1.0 for these experiments. And another point is the batch size, I set 16 for 640x192 and 8 for 1024x320 on single rtx6000 GPU
> > 
> > 
> > Hi author, I got worse results on a V100 GPU with torch 1.1.0 and I guess the version of other packages can also influence the results. So can you share the conda environment '*.yaml' file with us?
> 
> what numbers you've got? I have V100 and I will train a model on that to see what gonna happen

Sorry for the late reply. I try it again yesterday and got resonable results this time. Thanks for your nice work!
