### ISSUE TITLE
run-time FPS

### ISSUE THREAD

**Issue by takisu0916** [brandleyzhou/DIFFNet#26]
This is a great work. I have a question about "run-time FPS". In Table.3 of your paper, you claim that the run-time is 87FPS. Under what circumstances do you get this value? It takes at least 53ms for me to use GPU Nvidia RTX3090 to process a picture (640x192).

**Comment by brandleyzhou** [comment]
Sorry to reply late. Many factors affect the inference speed, like hardware, batch size, etc. We got these results in Table.3 on an RTX6000 card with batch_size = 16.

Hang
