### ISSUE TITLE
test on video

### ISSUE THREAD

**Issue by Hyyzhangrui** [brandleyzhou/DIFFNet#27]
Hello, would like to ask you a question. 
The input to the model is a video, how to generate a video after a depth estimate?
Can you tell me how to fix it? Thanks!

the best, 
Rui Zhang

**Comment by brandleyzhou** [comment]
Hi Rui,

The input to the model is a single image. if you want to generate corresponding depth from a video, you need first split the video into a set of frames, feeding them into the model separately. Then you can convert the generated depth maps to a gif or video file with some available tools.

Hang

**Comment by Hyyzhangrui** [comment]
Hi.
Thank you very much for your quick reply. I'll go and finish it. 
Have a great life.

best,
Rui
