### ISSUE TITLE
Missing Keys in 1024x320 Pretrained Weights

### ISSUE THREAD

**Issue by turi-mate** [brandleyzhou/DIFFNet#28]
Hi @brandleyzhou! Thank you for your work!

I met a problem when testing your pretrained models:

```
RuntimeError: Error(s) in loading state_dict for HRDepthDecoder:
       Missing key(s) in state_dict: "convs.72.ca.fc.0.weight", "convs.72.ca.fc.2.weight", "convs.72.conv_se.weight", "convs.72.conv_se.bias", "convs.36.ca.fc.0.weight", "convs.36.ca.fc.2.weight", "convs.36.conv_se.weight", "convs.36.conv_se.bias", "convs.18.ca.fc.0.weight", "convs.18.ca.fc.2.weight", "convs.18.conv_se.weight", "convs.18.conv_se.bias", "convs.9.ca.fc.0.weight", "convs.9.ca.fc.2.weight", "convs.9.conv_se.weight", "convs.9.conv_se.bias", "decoder.2.ca.fc.0.weight", "decoder.2.ca.fc.2.weight", "decoder.3.ca.fc.0.weight", "decoder.3.ca.fc.2.weight", "decoder.4.ca.fc.0.weight", "decoder.4.ca.fc.2.weight", "decoder.5.ca.fc.0.weight", "decoder.5.ca.fc.2.weight".
       Unexpected key(s) in state_dict: "convs.72fSE.fc.0.weight", "convs.72fSE.fc.2.weight", "convs.72fSE.conv_se.weight", "convs.72fSE.conv_se.bias", "convs.36fSE.fc.0.weight", "convs.36fSE.fc.2.weight", "convs.36fSE.conv_se.weight", "convs.36fSE.conv_se.bias", "convs.18fSE.fc.0.weight", "convs.18fSE.fc.2.weight", "convs.18fSE.conv_se.weight", "convs.18fSE.conv_se.bias", "convs.9fSE.fc.0.weight", "convs.9fSE.fc.2.weight", "convs.9fSE.conv_se.weight", "convs.9fSE.conv_se.bias", "decoder.2.fc.0.weight", "decoder.2.fc.2.weight", "decoder.3.fc.0.weight", "decoder.3.fc.2.weight", "decoder.4.fc.0.weight", "decoder.4.fc.2.weight", "decoder.5.fc.0.weight", "decoder.5.fc.2.weight".
```

The pretrained weights are downloaded from this repository, I was testing 4 models:

- [640x192](https://drive.google.com/file/d/1ZQPZWsIy_KyjV-Et6FSCOPM4iATjDPn-/view)
- [640x192_ms](https://drive.google.com/file/d/1_vh1F_cabTlEjBGXkHZOpAB1CMLmosxg/view)
- [1024x320](https://drive.google.com/file/d/1SuyBMS3ZLYuZwgyGSpmNrag7ESjRUC52/view)
- [1024x320_ms](https://drive.google.com/file/d/1VR0BYXKyclvv1Gq2XcQCR-fvJuFQ80SI/view)

I only experienced the problem with the [1024x320](https://drive.google.com/file/d/1SuyBMS3ZLYuZwgyGSpmNrag7ESjRUC52/view) model. Could you please have a look at what the problem might be? Thanks in advance!

**Comment by brandleyzhou** [comment]
Hi. In fact, they are not missing, and they are given different names(unexpected keys) when initializing depth net. It is because [1024x320](https://drive.google.com/file/d/1SuyBMS3ZLYuZwgyGSpmNrag7ESjRUC52/view) was trained with an older version HRDepthDecoder. Only these key/ module names matter, the values (models' weights) will not be impacted. So you can simply map these keys to new keys. e.g. change key name "convs.72fSE.fc.0.weight" to "convs.72.ca.fc.0.weight" before loading state_dict onto model.

I hope my answer can solve your confusion.

**Comment by turi-mate** [comment]
Hi, thanks for the quick reply and clarification!
Maybe you could put this into [README](https://github.com/brandleyzhou/DIFFNet#readme)?
