### ISSUE TITLE
Loss

### ISSUE THREAD

**Issue by wangcong607** [brandleyzhou/DIFFNet#4]
Hello，
When I run the code, I wonder whether you used the options of uncertain_mask and flipping_loss. Because I can't reproduce the accuracy in your paper at the resolution of 1024*320. Thanks for your reply.

**Comment by brandleyzhou** [comment]
nope, uncertain_mask and flipping_loss are not involved. when using 1024x320 images, we set the batch_size = 8, maybe it makes the difference. and could you tell me the numbers you got when reproducing?

**Comment by brandleyzhou** [comment]
Sorry for the misunderstanding. I think the reason is in hr_layer.py, the Attention_Module, please uncomment "#self.ca = ChannelAttention(channel)" instead and the related part in forward function. If it was still unsolved, I would retrain a new model myself

**Comment by wangcong607** [comment]
Thanks for your patiently reply, I will try again.

**Comment by wangcong607** [comment]
After adding the channel attention module, my result is 0.100 0.754 4.383 0.177 0.903 0.967 0.983.

**Comment by brandleyzhou** [comment]
Hi there, I have retrained a HR model, and  the result is  &   0.098  &   0.724  &   4.340  &   0.174  &   0.905  &   0.967  &   0.984 \\.  the best one is after 14th epoch  using pytorch1.10. which version are you using? Maybe numbers depend on the pytorch version

**Comment by wangcong607** [comment]
Hi, my pytorch version is 1.7.0. And I will try again. Thank you.
