### ISSUE TITLE
the layer's names of the decoder model and the depth.pth in diffnet_1024x320_ttr are not the same

### ISSUE THREAD

**Issue by czh0001** [brandleyzhou/DIFFNet#5]
hello, it seems that the layer's names of the decoder model and the depth.pth in diffnet_1024x320_ttr are not the same and cause error when running evaluate_depth.py

**Comment by brandleyzhou** [comment]
Thanks for your reminder. those available trained models are trained with an old version code.  I plan to upload the new models next month. Or you can instantly train models by yourself.

**Comment by czh0001** [comment]
OK, thanks for your reply!
