### ISSUE TITLE
issue about downloading hrnet pretrained on ImageNet

### ISSUE THREAD

**Issue by seb-le** [brandleyzhou/DIFFNet#7]
First of all, thank you for sharing this cool work. 

I faced an issue that an error occurred when I run the start2train.sh.

The error is below:
![image](https://user-images.githubusercontent.com/74757131/145160141-2a4e0344-d95f-44e0-886f-7fe6257e50bf.png)

I ran start2train.sh on another computer that has a different IP address, 
but the error also occurred.

Thank you.

**Comment by brandleyzhou** [comment]
Hi, Thanks for your interest. You could try to download the pretrained model manually and save it to a specific path. the hrnet18 url is in the same test_hr_encoder.py. If you have any problem , feel free to ask.

**Comment by seb-le** [comment]
How can I manually download that file?

I tried downloading in two ways:
(1) directly access the URL through an internet browser.
There is no response from the server.
(2) use "wget".
I faced the same error message. "ERROR 429: Too Many Requests."

Thank you.

**Comment by brandleyzhou** [comment]
It seems that the website is down, I  have uploaded the pretrained models on google drive, now you can download it via https://drive.google.com/file/d/1L3fhnNiLPFF0aNdhT52hlLykUOfu04pW/view?usp=sharing

**Comment by seb-le** [comment]
Thank you for your kindness.

Now, I can run the code.

Thank you.
