### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by seb-le** [brandleyzhou/DIFFNet#8]
Hi, thank you for sharing your nice work.

Could you share the environment setting such as versions of packages for this work?

I cannot reproduce the results of this paper even if using the pretrained model that is provided in this repo.

In my evaluation:
0.1024    0.7632    4.482    1.799    0.8954    0.9645    0.9831

In the paper:
0.102      0.764     4.483     0.180    0.896      0.965      0.983

**Comment by brandleyzhou** [comment]
Can you show your reproduced results? my torch version is 1.1.0. I think the reason why your evaluation of the trained model is different from the paper is that the printing format.

**Comment by seb-le** [comment]
As your mentioned, I tried to evaluate the official model of this repo on torch 1.1.0.
But, I still faced different results from the paper.

Below is the results by monodepth2 evaluation code:
![image](https://user-images.githubusercontent.com/74757131/148757292-f559e134-4eae-49b7-b6ed-f3ff0467a40e.png)

More precisely:
0.10242	0.76323	4.48215	0.17993	0.89543	0.96449	0.98312

Thank you.

**Comment by brandleyzhou** [comment]
Sorry for replying to you late. I have retrained and evaluated a model and what I got is 
![image](https://user-images.githubusercontent.com/56123087/150637463-139dec1e-e29f-4df0-9b59-7011de2548a6.png)
The model named diffnet_640x192 is available on google drive.

**Comment by seb-le** [comment]
Thank you for your kindness!

I downloaded and evaluated it.

Although there are some differences between your test and my test, it is very minor.

![image](https://user-images.githubusercontent.com/74757131/150728772-02b61c44-885d-489f-ad4c-6f625dd85ae8.png)

Again, I appreciate your kindness, 

and I have really learned a lot thanks to your source code and your paper.

Thanks.
